server:
  port: 8055


spring:
  datasource:
    url: jdbc:mysql://172.16.106.22:3399/hansight?useUnicode=true&characterEncoding=utf8
    username: hansight
    password: hansight
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select !
      test-on-borrow: true

  redis:
    host: 172.16.106.22
    port: 6379
    password: cloud@hansight.com
    database: 1
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 100
        # 最小空闲连接数
        min-idle: 20
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  3000
        # 最大活跃连接数，负数为不限制
        max-active: 100



# 注意注意
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hansight.springbootmybatis2.demo.pojo
# 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
  configuration:
    map-underscore-to-camel-case: true

es:
  clientCount: 2
  clusterName: hansight-enterprise
  addresses: 172.16.106.22:9200
  enableSSL: false
  sniff: true
  sniffTimeout: 30000
  maxRetryTimeout: 30000
  connectTimeout: 1000
  socketTimeout: 30000
  connectionRequestTimeout: 0
  toThreadCount: 10
  maxConnPerRoute: 10
  maxConnTotal: 30
  buckSize: 1000

vul:
  clientCount: 1
  address: 172.16.100.202:443
  enableSSL: true
  maxRetryTimeout: 30000
  connectTimeout: 1000
  socketTimeout: 30000
  connectionRequestTimeout: 0
  toThreadCount: 10
  maxConnPerRoute: 10
  maxConnTotal: 10

kafka:
  bootstrap.servers: 172.16.106.24:9092
  group.id: hansight-kafka-es
  enable.auto.commit: true
  auto.commit.interval.ms: 1000
  session.timeout.ms: 30000
  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  poll: 1000
  topics: event

  control.offset: true
  offset: 0
#logging.config: ./logback.xml